### ISSUE TITLE
Correção da AC2

### ISSUE THREAD

**Issue by victor0machado** [mncbl/PROG-OO#1]
Esse trecho poderia ter ficado fora do `switch`. Terminou que cada `case` ficou com uma interface diferente...

https://github.com/mncbl/PROG-OO/blob/024068cb3b397c02963e7b9f62e8293ca018c34c/AC2/calculadora/src/App.java#L76-L88

**Comment by mncbl** [comment]
Corrigido o posicionamento dos if
